### PR TITLE
Bump slim-rails to 3.x

### PR DESCRIPTION
**Pull request by arthurnn**
Bump slim and fix deprecations. slim-rails 3.x is compatible with rails 4.2.x

### CODE REVIEW

**Comment by phoet** [comment]
Thx Arthur, I think I have a rails 4.2 branch open somewhere...

**Comment by arthurnn** [comment]
sweet... this will help you on that branch.. merge this and rebase your branch! :tada:

**Comment by PragTob** [comment]
Wow it's @arthurnn ! Thanks for your work here and over on @rubygems :) @sferik gave you a shout out yesterday. Keep doing what you do :heart:

**Comment by phoet** [comment]
All the <3 for arthur
Am 09.01.2015 21:03 schrieb "Tobias Pfeiffer" <notifications@github.com>:

**Comment by arthurnn** [comment]
:heart: :yellow_heart: :purple_heart: :green_heart: :heart:

**Pull request merged**
