### PR TITLE
make url editable

### PR DESCRIPTION
**Pull request by bitboxer**
I just found out that my url is not editable. I added the field to the form. 

Warning: I could not test it this morning because I could not setup the twitter / github login locally.

### CODE REVIEW

**Comment by phoet** [comment]
@bitboxer the `script/server` script should have all necessary tokens configured for local development

**Comment by phoet** [comment]
and in development there is a `get '/offline_login/:nickname',  to: 'sessions#offline_login'` route

**Comment by bitboxer** [comment]
Ah, perfect. Good to know. This morning I just got a 404 on github...maybe I did not seed correctly or something...

**Comment by phoet** [comment]
@bitboxer github login is a bit tricky as it does not support arbitrary callback domains. so i think there are 2 tokens configured for testing those local domains:

http://onruby.dev:5000
http://rug-b.dev:5000

**Pull request merged**
