### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by phoet**
i rebased the old docker branch against master and incorporated some changes from @iGEL and @bascht

one thing that bothered me was to re-install gems every time the `Gemfile` changes, so i tried [an approach with an ephemeral container volume](https://medium.com/@fbzga/how-to-cache-bundle-install-with-docker-7bed453a5800#.ost3nqpjp).

another unsolved issue was handling the different host-names. for that i created `script/open` that looks for the active docker-machine and generates an url using [xip.io](http://xip.io/), that just used to work without any code-changes :sparkles: 

next step would be to use travis docker-service to run the same setup there and run tests on it.

### CODE REVIEW

**Comment by bascht** [comment]
:+1: Like it. Also: Kudos for shipping around the `/etc/hosts` hacks. I tried to mix up something to get this up and running on Travis. PR coming up.

**Comment by bascht** [comment]
Oh geez. looks like port 5432 is already bound inside the Travis build env. :-|

**Comment by phoet** [comment]
@bascht i don't have time right now to iterate on this. i gave you access to the main github repo in case you like to finish up on this

**Comment by bascht** [comment]
@phoet Thanks! I try not to set anything on fire. :+1:

**Comment by phoet** [comment]
thank you :smile_cat:

**Comment by phoet** [comment]
just FYI if you merge into master that will get auto-deployed

**Comment by bascht** [comment]
@phoet Green, but those 21 »let's try this  / that« commits aren't that helpful. Should I squash this branch / cherry-pick it to a new PR?

**Comment by phoet** [comment]
I dont mind,  what you feel most comfortable with

**Comment by phoet** [comment]
And :party: for :green_apple:

**Comment by bascht** [comment]
@phoet Rebased and cleaned up: https://github.com/phoet/on_ruby/compare/master...bascht:docker If I may, I'll force push to `phoet/docker`.

**Comment by phoet** [comment]
Go ahead

Bascht <notifications@github.com> schrieb am Fr., 23. Okt. 2015, 09:56:

**Pull request merged**
