### PR TITLE
use one signal instead of zeropush for ios push notifications

### PR DESCRIPTION
**Pull request by mnin**
Because "ZeroPush has joined Twitter!" and will be closed.

### CODE REVIEW

**Comment by bitboxer** [comment]
Just out of curiosity: how do I register for this push notification?

**Comment by phoet** [comment]
@bitboxer there is an onruby ios app in the appstore!

**Comment by mnin** [comment]
@bitboxer http://appstore.com/onruby

**Comment by phoet** [comment]
LGTM :shipit:

**Pull request merged**
