### PR TITLE
fix zoom map to every Usergroup configuration into yml

### PR DESCRIPTION
**Pull request by stbnrivas**
Hi phoet, I would like use a customize zoom level.

Thanks a lot in advance

### CODE REVIEW

**Comment by phoet** [comment]
@stbnrivas could you check why one of the tests is failing on CI?

**Comment by stbnrivas** [comment]
of course I can, sorry about. before to merge, it will change zoom level for all UserGroup, maybe necessary reset to 12 into, Hamburg, Berlin, leipzig... Sorry

**Comment by phoet** [comment]
@stbnrivas yeah, could you do the reset as well?

**Comment by stbnrivas** [comment]
done, thank you to let me colaborate

**Comment by phoet** [comment]
thx @stbnrivas

**Pull request merged**
