### PR TITLE
Madridrb import

### PR DESCRIPTION
**Pull request by kikito**
Hi there,

This is a rake task to import old Madrid.rb data into the existing database. It should be as simple as running this on the server:

    rake madridrb:import:meetings

I *strongly* recommend testing this command on a dev machine with a db dump from production (I could not figure out how to make one).

This script does the following:
* Import locations from a locations.yml file
* Import users from a users.yml file
* And then import event info from a meetings.yml file - including topic and speaker info, additional materials (videos) and attendees (when possible).

I did my best to make all commands idempotent (i.e. they try to find a user before creating a new one). So running it several times should work just fine.

About the code: This being a one-off thing, depending on a very particular yaml config file, I didn't bother making the code clean, elegant, uncoupled, nor tested (hence my strong recommendation to test it on a production dump first). It is all in a single file + dir so the uglyness is isolated. Once the data is in production, this PR can be reverted (I would imagine the code quality and test coverage will drop a bit when/if this is merged)

### CODE REVIEW

**Comment by phoet** [comment]
looks good, i just did one change to handle users that have been registered already on the platform using github:

```
  def find_user_by_twitter(handle)
    handle = handle.split.first.strip
    handle = handle[1..-1] if handle[0] == '@'
    User.where('lower(twitter) = ? OR lower(github) = ?', handle.downcase, handle.downcase).first
  end
```

if you want to get a local copy of the data i need to add you as a colaborator to the heroku app. what is your e-mail address used there?

once you have access you can get a dump of data like this:

```
rake db:drop:all
heroku pg:pull HEROKU_POSTGRESQL_MAROON_URL onruby_development
```

**Comment by kikito** [comment]
Hi there, I don't think the change is needed (all the registration data we have is from twitter) but it should work all the same.

My email is kikito at gmail dot com.

**Comment by phoet** [comment]
sorry, i did not make myself clear. it IS needed because existing data might not have a twitter handle at all.

**Comment by kikito** [comment]
But of course you were totally right. I was able to download the database and (once I made the change to match github as well as twitter) everything seemed to import well.

Please run the rake command on the heroku server when you want (I would recommend making a db snapshot before, just in case).

Regards!

**Comment by phoet** [comment]
```
Lost members: @1hourl8r,@AlvarOS_anchez,@GustavoCsso,@carlosve_ucv,@dani_capello,@daniel.oton,@dsromero_,@egimenez_com,@etnlmy,@fandrod,@fothdev,@frsevillano,@izgaka,@jmdlta,@jorgesangarr,@josemspain,@luismierre,@manu1621,@mikelci,@negrolongi,@rafa.diaz,@raulbarrosoleon,@samudeas,@santiriera626,@sigilioso,@xtremevoodoo,@zirodev,Alex_r,AndresBarriga,Andrés Barriga,César,David Z,David Z.,Erkan,Etienne L.,Gustavo,Gustavo Caso,Igor Rootsi,JRodriguez,Jorge Ruiz,Julio,Marvin,Marwan,Unai Trecet,alia-del-crys,andresBarriga,braisomary@gmail.com,davidz,etd,jose luis,jose_luis,josé luis,manu,Álex
```

everything else looks good. going to revert the change once we are confident everything is fine.

**Comment by phoet** [comment]
had to upgrade the postgres database to a paid plan because we are now over 10k rows :smile:

**Comment by kikito** [comment]
Awesome, thanks!

I gave this a cursory look and it looks fine. I will look at it a bit more closely this afternoon. Then I can revert the change myself (it that's ok with you).

The "lost members" message was expected. In our previous wiki people could "register" pretty much with anything they wanted - we used twitter "by convention", but people also used their names or made up inexisting twitter accounts.

> had to upgrade the postgres database to a paid plan because we are now over 10k rows

On that regard, madrid.rb has some sponsors, so we would be happy to pay for that cost (we can discuss it via email if you want)

**Comment by phoet** [comment]
@kikito if your sponsors can offer some help, that would be great! feel free to ping me any time

**Pull request merged**
