### PR TITLE
Switch to docker-compose + add docs.

### PR DESCRIPTION
**Pull request by bascht**
I already started to add my own docker-compose.yml but it looks like your branch was doing all that already (except for the name change Fig → Compose). All in all, your branch looks master-mergeable anyways.

### CODE REVIEW

**Comment by phoet** [comment]
@bascht thx, i completely forgot about doing this in the first place :)

if i find some time i'm going to setup a proper [heroku-docker thingie](https://devcenter.heroku.com/articles/docker).

**Comment by bascht** [comment]
Whoops. Looks like the build [blew up](https://travis-ci.org/phoet/on_ruby/builds/86009574) and the `docker` branch is also waaaaaaaaaaaaay behind `master`, so I it'll need a good rebase, but – as I just wanted to add a new city, this has already gotten to big of a yakshave. :D

**Comment by phoet** [comment]
@bascht if just want to add a new city would it be ok for you to do that on the none-docker-master? otherwise i can find some time to make it pass so you can work on it.

**Comment by bascht** [comment]
@phoet sure. I'll test my stuff on the docker branch and just rebase it to `master`. If it's not one of your biggest priorities, I can also see if I can polish the docker branch later. :)

**Pull request merged**
