### PR TITLE
Update to Ruby 2.4.0

### PR DESCRIPTION
**Pull request by skade**
I had some issues getting a development environment running using the docker method. (e.g. bundler being outdated for the Gemfile)

I decided to just bump everything to 2.4.0 and it seems to work.

Let's see what travis says.

### CODE REVIEW

**Comment by phoet** [comment]
@skade too bad 😢

i pushed latest ruby and rails 4.2.8 to master, you can apply your changed on top of that.

i'm not happy with the feedjira testing stuff right now. it also spits out a couple of warnings. i did not want to use vcr, but the faraday-testing-adapter instead. i needed [to patch feedjira](https://github.com/feedjira/feedjira/pull/374) in order to do that, but the latest version should have the changes included.

**Comment by skade** [comment]
Either I'm missing something or the feedjira patch doesn't help that much.

Faraday does only take a symbol as _#default_adapter_ and we'd need to pass in a full

**Comment by phoet** [comment]
to be honest, i don't know either, i was referring to this though https://github.com/lostisland/faraday/#using-faraday-for-testing

**Comment by skade** [comment]
Argh, sorry, wanted to hit "close" without commenting.

Fix is here: https://github.com/phoet/on_ruby/pull/257

**Pull request closed without merging**
