### PR TITLE
Madridrb label

### PR DESCRIPTION
**Pull request by kikito**
Hi there, here's my PR for Madrid.rb. I've got several notes:

* The locale generation code had :de and :en locales hard-coded, I have fixed it so it uses all the available ones (https://github.com/madridrb/on_ruby/commit/f3ba5b771d6af31001c4f25a545bea189d549d34)
* As we've talked in another issue, I had to downgrade ruby to 2.1.1 to make it work ( https://github.com/madridrb/on_ruby/commit/fe1d2d61126d8d39573c92a3c6a924a1773db61c )
* My group meets "the last thursday of the month". The site allowed creating events for the first, second, third and fourth day of the month, but not the last, so I have added it, with tests ( https://github.com/madridrb/on_ruby/commit/c4c832ee7aab66b340f894098344996f2501c7c4 ). I also made the ordinals work better in English and Spanish, where we say "first" or "primero" instead of using numbers ("1."), like in German. On that note, I don't know if "jeden letzten Donnerstag im Monat" is proper German, please change that if needed.
* I corrected minor things in the three locales, the most important one being a missing twitter link.
* I have also added a Sponsors field to the usergroups. Sponsors are not a model, but their banners appear in the footer of the page (unless the usergroup has no sponsors, then nothing is rendered, so existing groups should not be affected). The change is in https://github.com/madridrb/on_ruby/commit/6b0804dc0f704366c1af70dcc6761ee8dbf6a065 and it looks like this:

screen shot 2015-01-18 at 13 53 12

Since this is the beginning of the year, I'm doing the sponsorship rounds, so it is possible that that list changes a bit; I might have to correct it with another PR in the future.

Another thing that I have not even tried yet is handling the videos at all. I will attempt to do so in a separate PR.

### CODE REVIEW

**Comment by kikito** [comment]
Travis was failing because it did not have ruby 2.1.1 there. I have downgraded it in travis too.

**Comment by phoet** [comment]
@kikito this is great work :green_heart: sorry for the issues with ruby 2.2.0 i hope this can be fixed soonish.

is `madridrb.com` going to be the proper domain? should we acquire onruby.es as well?

i'll start rolling this out, so we can have it up and running as http://madridrb.onruby.de until we figured out what to do with the domains.

**Comment by phoet** [comment]
@kikito it's running on heroku now. please log in via github or twitter so that i can add administrator privileges to your account.

**Comment by kikito** [comment]
@phoet : logged in with my github account. It seems I made a mistake when I filled up the whitelabel.yml file - it is trying to go to onruby.**org** and failing. I will fix in another pr

**Comment by phoet** [comment]
yeah, that won't make much sense until we have an authorative domain like onruby.es or the like.  

i added you to the admins, you can edit stuff here: http://madridrb.onruby.de/admin/dashboard  

--  
Peter Schröder
Señor Developer @Jimdo

**Comment by kikito** [comment]
I confirm that I was able to enter, thanks!

As I mentioned, this is still not the definitive site - I still need to check with all the sponsors, and figure out a way to handle the videos nicely. But it is definitively a good start! Thanks for your support :)

**Comment by phoet** [comment]
:+1: ping me if you need anything

**Pull request merged**
