### PR TITLE
sanitize html in markdown content

### PR DESCRIPTION
**Pull request by lukad**
Currently user input in the user profile description is not sanitized and allows arbitrary HTML including script tags.

### CODE REVIEW

**Comment by phoet** [comment]
👌

**Comment by phoet** [comment]
screen shot 2018-07-09 at 21 01 40

**Comment by phoet** [comment]
sollte man vielleicht standardmäßig als profil-text hinterlegen 😄

**Comment by phoet** [comment]
FYI onruby uses https://hakiri.io/ for security scanning of dependencies and code analysis. i forwarded this issue, maybe they are cool and add it to their checks.

**Comment by lukad** [comment]
Good idea. 👍

**Pull request merged**
