### PR TITLE
Prague.rb

### PR DESCRIPTION
**Pull request by thepeklis**

### CODE REVIEW

**Comment by phoet** [comment]
can you please:

* provide a decent description to this PR
* exclude the `.idea` directory
* clean up your commits
* keep in mind that you must not change anything except your user-groups specific translations/settings/templates

for some context: the website runs as a mutli-tenant application, so all websites and domains are served from one heroku app.

**Comment by phoet** [comment]
@thepeklis is this a work in progress?

**Comment by thepeklis** [comment]
Hi, sorry about the delay..
could you please specify what should i do about those bad commits?

**Comment by phoet** [comment]
@thepeklis if you don't know how to [change git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) that is no show-stopper, i can take care of that later on.

you need to add the `.idea` folder to `.gitignore` but make sure to remove that folder and commit those changes before adding it there.

**Comment by thepeklis** [comment]
@phoet the changes are done, but as it turned out, i totally suck at working with git since i haven't done it before. My colleagues are experienced so they'll help me tomorrow. thanks for your help.

**Comment by phoet** [comment]
@thepeklis great if you have someone backing you up

**Comment by phoet** [comment]
closing this for now. please re-open it if you are making any progress

**Pull request closed without merging**
