### PR TITLE
Add Rubyshift Munich.

### PR DESCRIPTION
**Pull request by bascht**
I did find an old version of the Rubyshift in the repo, brushed it up a bit & would love if Munich could finally join the fine ranks of onruby.de :smile_cat:

### CODE REVIEW

**Comment by phoet** [comment]
That would be great! Are you sure that the munich community actually wants
to use it? When I recall correctly, we had a lot of trouble the last time
and in the end had to redirect from onruby to the Munich community site.

Bascht <notifications@github.com> schrieb am Mo., 8. Feb. 2016, 02:52:

**Comment by bitboxer** [comment]
Bascht is the new organizer, so I think he is pretty sure :wink:

**Comment by PragTob** [comment]
Yay for @bascht !

**Comment by phoet** [comment]
@bascht i will try to get this setup tonight.

**Comment by bascht** [comment]
Co-Organizer, but close. :smile_cat: I dug up an [old thread](https://groups.google.com/forum/#!searchin/rubyshift-muenchen/onruby/rubyshift-muenchen/xg3A3q74OqM/aX6LsU5wVFoJ) and as none of the people involved are still active in the user group, I see no reason why we shouldn't be here. I guess we're still stuck with meetup.com for the orga / announcement stuff, but at least Munich is no longer missing from that list. :smirk_cat:

**Comment by phoet** [comment]
:shipit: http://munich.onruby.de

**Comment by bascht** [comment]
@phoet <345! THANKS!

**Pull request merged**
