### PR TITLE
add andalucia.rb group ;-)

### PR DESCRIPTION
**Pull request by stbnrivas**
Hi phoet, we are create a small ruby group in Andalucia, Spain. We want to join to onruby.
Thank you so much

### CODE REVIEW

**Comment by phoet** [comment]
@stbnrivas i merged your PR and i've hooked up the DNS so that your domain should be up in a little while https://andalucia.onruby.eu/ 

in case you would want to add a custom domain, please ping me over here so we can hook it up properly.

i added you as an admin, so if you are logged in, you should be able to access `/admin` path. since all our usergroups share a common data-source, you might be seeing other groups data, ie user accounts. if you have any questions concerning the admin interface, feel free to ask.

cheers, and good luck with andalucia ruby usergroup!

**Comment by stbnrivas** [comment]
Thank you so much, Yes I can login as admin. Cheers!!

From now onruby.eu domain is perfect. I played with admin interface in local installation... I will be very careful. Thank you

**Comment by phoet** [comment]
great! if you have any questions, feel free to ask them here or ping me on twitter

**Comment by stbnrivas** [comment]
I am not sure, github login works but the login with twitter it doesn't work, Maybe by it is require add new url callback into API twitter, or I need do something?

Thanks in advance

**Comment by phoet** [comment]
@stbnrivas true, i had a typo in the url. unfortunately twitter requires a whitelist for callback urls as of some month ago. that really did not help our case...

**Comment by stbnrivas** [comment]
ok, then I will wait, many thanks again @phoet

**Comment by stbnrivas** [comment]
It works, thank you @phoet

**Pull request merged**
