### PR TITLE
More changes in Sponsors in Madrid.rb

### PR DESCRIPTION
**Pull request by josepegea**
Yet another change in Sponsors in Madrid.rb
Thanks!

### CODE REVIEW

**Review by phoet — APPROVED** [review]
🤑

**Comment by josepegea** [comment]
> 🤑

Haha! Not really. It's more than old sponsors are changing branding and want to add new identities. Looking forward to see the group really grow 😅

Hoping it's Ok that I merge this

**Comment by phoet** [comment]
Sure, feel free to merge things right away if they are just for your Meetup. 

I try to add screenshots whenever I make visible changes, so that it's easy for others to argue about it without having to run the new code.

**Comment by josepegea** [comment]
Thanks. And will try to keep in mind the screenshot idea for new PRs!

**Pull request merged**
